{% set version = "0.18" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-extrafont
  version: {{ version|replace("-", "_") }}

source:
  fn: extrafont_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/extrafont_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/extrafont/extrafont_{{ version }}.tar.gz
  sha256: 44e6a9798914b99c1460a1177c1f1503cf2a2f74844e3e7858fb98462b08a857

build:
  noarch: generic
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rttf2pt1
    - r-extrafontdb

  run:
    - r-base
    - r-rttf2pt1
    - r-extrafontdb

test:
  commands:
    - $R -e "library('extrafont')"  # [not win]
    - "\"%R%\" -e \"library('extrafont')\""  # [win]

about:
  home: https://github.com/wch/extrafont
  license: GPL-2.0-only
  summary: Tools to using fonts other than the standard PostScript fonts. This package makes it easy to use system TrueType fonts and with PDF or PostScript output files, and with bitmap output files in Windows. extrafont can also be used with fonts packaged specifically to be used with, such as the fontcm package, which
    has Computer Modern PostScript fonts with math symbols. See https://github.com/wch/extrafont for instructions and examples.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
