travis:
  secure:
    BINSTAR_TOKEN: Q9R+wMQ94kFXJNbj7ZRalfK7GBQpRgO4oJbxQpB2fFTSklb28BBko3jIbIIhPXLd4Gt6pSKmHtlUfcLdhQ/mqG8aHa4oyzBWxwpKmTvaoCmqLxCiO4dE84d5Xngs2J2n7cTbaHOddvBDZKncNep5shhf4jRfqFCMjrooD1bQAAIK3lpbZXOnYQXbSKaK9D5rD9yOTz/+r93C+27+eEKim6y4wEQoZEnpKwpfP4IPD6oZ/GU4gP6KdXtu9uV720S28KgS+D59UqjJKk3minIpwTF3wFMZOzUMUhf26wutbJDWlhySMBtM4xrw8hlODmv1yAsqxoSbzGhWYJDdSUggJDXyzu9D7yO8uuPCTzYv5qsF4VrwpkyJ0B+pOUamD3QBwVq5As0oZErpfkmztk7ozRY+vewscAA9pEH7c36/eYQIay3w6GJIt7y1HxIBiEKPL3X4LSXgMeLGum9VyGlxWH0qRtzdo86LeTYaIf2r9C6PrK5REDhaRX8W974QsRBzJF7Zk/t1PpY2U9GF4KdzFprKM+HXp2o1dXXroZQVCHJ+d4eQK2ajyF2pAurUuhMgtAeM0/DmH3IM0gacoZxw0OBSMzBrhUw4nQM5o1G+1RYp9SPt3vwmUzLYIpRcyPYghL9fA3VBjNkefhrL90M5vH3Ft6C6Zo46YU+ltCLh6Vs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
