travis:
  secure:
    BINSTAR_TOKEN: UW13NJBck2rZxsj5JB7iXBJT4utItfVzwDTuu+qWPvEiXmi9ZojQnO9NaHCQDR09pDxw5aurUKwmWIrnm6H5nE+FOwGzWVSu5F5hnw+wlSpJChIzY/wXLMO5D/WpvM8fzVU4EzlJo/HlszWZaT85u3wLzmcgrQjYXWkkWnV5Zmcxhn3QLcpdvKB8DKzhIUxQsMkHMy98tVEWQfo+fTN32WPzpzZNQIL7lBj5BC1PRpnzQwxtOvlZTlGLsIMCM20hIMLL8aG5WIXIFlEoB9guWZaYhMAzEKlgCMOjepmZLW75JDbHgfYMDe/byHj6iDFYa1nfIarObMXTFkku73TKWHK+D9BXdtN+OmpbPtgpx4zgovy6Wzq0A9GzzYg0OC+en6QDtWOzsuwTjUG96KJk3HxzsO3y/LuboEdQCk0XlLY4pF+A3lRTNoPGhmfQ9ca7csdWNse9Jvos/jTEcIcnKxxs/YENLDR12YNviFGYQtC23QwF1qxWzziNb6z3XCQDeLiH/nExA46CxM2bN8fmSSZ/hnPkQkoHNEaBwbTEoM57lIN3t7byyMO3xrgW7aY0jpSBJDlHJYXpqAwcitqjrkiuXKYLRA2rY39TX1CpNTPFC6aYTkdSTunJVwBWIQr1TLwPbMETITdSi4ERbyvr8rhX0GZcLTrMZC5AqL0MTIc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
