travis:
  secure:
    BINSTAR_TOKEN: AuyN3PkKws18tSpWIxjiYQfjwvbpfGNYqIhgNXhjuS2kdRwr6PgdOSjS0hpBOBy1JRSBTHKuYIOekd4/h3BMJzqJdRg8UV0vmy9MEtaQ7jMssjZou8LFaLTx75XlYkhB/XT8jIaf0W6kV2xzvg8KSRteLSHl2kJUPvRKa5u/VReahLy/gZhiXbkafcQ6WfPeXKFht/+eVsjAZE6lQAGFRrL4AgBqcjyLsju2YKtC1KKtA0q8XLZzv5ywdT8mP6w4rZo5/YfWYjvniiGtfJPGLoig3rFvECMT5z7jGIyxtjta8yToRnuuZzy7T4wMzpjP+/j6ubp5zBIzgY4RHPMDo+YRyGzP0Cxjh1lKC+LjusmdYQLOpasH1JuLbSapvVQT6XyMnJmYQLTFZNpCRBMkkVZ98lyVXIr5m4JZRlKegA/WajtVDLx+NBwI3ukXqLTgeLm3EMKMo+/euZFjiufz7Lg35zeYtHRE4OQWpN/tTAmH996xxgtsQrgF9EF9XS+tV/x9sq89jn9tEjIAVbLgHVNJZGC66x7irffOMbTEcs4VSD1pmvemrf4VI0kDPEZDoO3Fot9cwQBCgCDImhZQDVXXnyskvV4Nl0crxdS9I3QA2XE5hG3qpyDqdqounmhp697WPcc2h2FDsRxAkmeixJBtIFedRYo8b1Wjxj7C0cI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
