travis:
  secure:
    BINSTAR_TOKEN: TwLJpTJR9cC8WV1xRjLYYzGYpgKm/tBy7Fm5lhN5Tu5WkcFU/g/caNF0JD4Cf4oUYuYhTk10qCPKKqhlJL4nWmkC/4SZUN7UGlar+mbujOvAXLE3qYjwfGj9nDRf6+b24nOKZ1KUsQLqm2PmtEXWmSEAEheVCycpzv/+qGyM/Pk/CVf98LmE6Y0qlTFVAGQIWMOXdPwLs3Ii/XluXvgSJO/6KlJIf0Ly/THASrX9SuMo6gqFip7xnSwbbP1uqvnCDNyJJAUeKnSQZoZGQINuSl5dWG6Rlo8nuuUjyc0T4zGiBj9476tI4Clv89foEHNvYAVzuacV8qwjHabCk1A8DDXsVOqt3/hnv41uClPj0KbPK0Mi2NcV1XHwKb44kJFhJvvYLAFmPCEZyhyeb3V445WxSTuokVS3tghNpC6zgZsVFOAIR8Dn0yHkVvb9Z5uDsgYIxuo/JmCvB/zszmMVxLdNTTQNKG0cvG4UhTj/4YU3M3Q9l58XCMbfg3Ql3DcqGX0RjRx4y2fEFzWInIVu0Ngd3mcsbjQblJ11au+jRlKIJjtCGsLd8A3bwK0PGQBdqwcKqbOgjoDXYCNYiSbsKtEmCXX/GUH/TSnQ9fmVD29cHmUtAJaaYtDXrPwZV2FEIQTYiI0F32K4oG/QYoXp3S/rs1ENPMN5ufSqeoca7vw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
