travis:
  secure:
    BINSTAR_TOKEN: UtUBrcR9ev6ui15cZhLfv2XgpSsS1Yu4l6Y1wfbqmZ9Lt1zBYQJJWigL+oAPwHGYHpQQUj4OjgpIrsWAD/hKgX7qN0lyXoz3U9fL+6DgMM13xYfzbXSYRpJUQThGINeJCu0e/TvRX4i6YBXigttPH+B5ufufp4u8nJjV7KqUEbI0zTT/XVUxQ6C5FuQY8JcD+z3doCmW9MVIk0vYq6PuG1gDib9qsWRPVoW3KCpTNkujh+yg+twED1dHZ+jrD+8So0xM080axHQGf3iFkKnkpzWQ0x4uljG+9CxE0ZXMSNYVEW6bsaq46kr6ZwfaxjldCrVaMrU/4xO0RwWNhRXNwPJZm7pLpWViCrhOG9g849/nN17GJArZtcgU9rr9QkDMjKtksy+8Pro3eYFW1lddNw37e0qEzxrwDU7K3Cvfqu8g8l5vknJcwLAZnOaDpLN5kMMpK+AYo82F2i4RWo/3pfrVpQntV9LRzDmhMAmFWlCqRSmBdD2O6P2YM2SRUp+WcEw84eutEyQINXsIfM+5wfrPnvzQAh01FV0zfJC/p/xS+0ALBOOociy3pJfcwdZdaWtXCMi5B+LmTmtMfjhbMZE65u0tBxlHgq+wyNaMThkZdqRAwD2c4K6NWIoM7ACg/UUtzPlRlNHPjTIHMe2XuN46OHw0R/sj3bloAo5HKDw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
