appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: S1q1DMthm8fZG6ubVcsj8Q2PqgD1Xc9FzEhi9GhR3STJJ6XdwSPxSgPThFa7b+yPaOoeFJm0t/xEiw7oBSfy4AD2ysynA4dIQuWRVWRPo/uyxVLRarg/QPHLbiVGRF2yy93Pw6c9s4/FqN08pdCCZRS4ak/Anp0fQSGkaD39BTTm07TvBIWEbwb5S42+yv6heIXOMbXGO0n1O3C08MOK1fpN2g+1Hj2IZG8tVnu42ui6lpHKp/nJ3CPCLrCtb2rZbbKUAlIF8dvN9/HAmszOqO3nMfRVuu9jQsHvcbJrHmPtTyvvAjIr+4pzrQOAUeDNNcnVpdiZP8A4nUpqhft5l3fXb8KTkSom42/I/673Z7NDRlSTjqRx6Ai3ZLNXGmL6vLGTl5tKC7Hcw4M4LixlsNd5Va/3z1u2xPJ7JnGh8XKMbrimgzxj4RB1HwSJFUDSZQFVN8ELgqJ4xRP3XSvQIKt/yyIXf3cRXVB4b2z+CzSevs47IXBqAIqlU3f/ZPImKrJwBBmmmxC/YOE/1xsRZl/VM55NCzWy2o43xVJgkzvkX9tHOjUI+eF/wgc/7gx3MX71G4DvuqVkaHRgo0B8FXz2ejaw7MJD3neVMC6pX25CX2pGa1SxkSTCo8Fse3ttbz+JdSoJ/+ofGQLdycT26yq5rHpDfN3zTras0hIBLps=}
